---
- name: Create needed .ssh folder
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: SSH KeyGen command
  shell: |
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"

- name: Fetch the keyfile from the node to master
  fetch: 
    src: "~/.ssh/id_rsa.pub"
    dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
    flat: yes

- name: Copy the key add to authorized_keys using Ansible module
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
  #when: "{{ item != ansible_hostname }}"
  with_items: 
    - "{{ groups['virtual_servers'] }}"